services:
  keycloak-sp:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-sp
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8081
      - KC_HTTPS_PORT=8443
    network_mode: host
    command:
      - start-dev --import-realm --log-level=DEBUG
    volumes:
      - ./realms/internal.json:/opt/keycloak/data/import/internal.json
      - ./realms/SP_realm.json:/opt/keycloak/data/import/SP_realm.json

  keycloak-idp:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-idp
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8082
      - KC_HTTPS_PORT=8444
    network_mode: host
    command:
      - start-dev --import-realm --log-level=DEBUG
    volumes:
      - ./realms/IdP_realm.json:/opt/keycloak/data/import/IdP_realm.json

  app:
    image: python:3.12
    container_name: app
    volumes:
      - ./app:/app
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/bash -c "pip install poetry && cd /app && poetry install && poetry run python app.py"
