services:
  keycloak-sp:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-sp
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8081:8080"
    command:
      - start-dev --import-realm
    volumes:
      - ./realms/sp.json:/opt/keycloak/data/import/sp.json
    networks:
      - keycloak_network

  keycloak-idp:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-idp
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8082:8080"
    command:
      - start-dev --import-realm
    volumes:
      - ./realms/idp.json:/opt/keycloak/data/import/idp.json
    networks:
      - keycloak_network

  app:
    image: python:3.12
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - "8083:8080"
    depends_on:
      - keycloak-sp
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/bash -c "pip install poetry && cd /app && poetry install && poetry run python app.py"
    networks:
      - keycloak_network

networks:
  keycloak_network: