services:
  keycloak-sp:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8081:8080"
    command:
      - start-dev --import-realm
    volumes:
      - keycloak_sp_data:/opt/keycloak/data
    networks:
      - keycloak_network

  keycloak-idp:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8082:8080"
    command:
      - start-dev --import-realm
    volumes:
      - keycloak_idp_data:/opt/keycloak/data
    networks:
      - keycloak_network

networks:
  keycloak_network:

volumes:
  keycloak_sp_data:
  keycloak_idp_data: