KEYCLOAK_SP_URL = "http://localhost:8081/"
KEYCLOAK_IDP_URL = "http://localhost:8082/"
KEYCLOAK_INTERNAL_REALM = "internal"
SP_REALM = "SP_realm"
IDP_REALM = "IdP_realm"
KEYCLOAK_CLIENT_ID = "app"
ADMIN_USER = "admin"
ADMIN_PASSWORD = "admin"
